language: node_js
node_js:
  - "6"
  - "8"
before_install:
  - stty cols 80

dist: trusty
sudo: required

group: edge

addons:
  firefox: "53.0"
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
install:
  - npm install
  - git clone https://github.com/alexey-semikozov/resolve
script:
  - npm run test:firefox
  - cd resolve
  - npm install
  - npm run bootstrap
  - cd examples/todo
  - npm run test:e2e
